create extension if not exists pgcrypto;

create table if not exists public.institutions (
  id bigint generated by default as identity primary key,
  name text not null,
  type text not null check (type in ('liceo', 'utu')),
  department text not null,
  address text not null default '',
  lat double precision not null,
  lng double precision not null,
  description text not null default '',
  images jsonb not null default '[]'::jsonb,
  has_dining_room boolean not null default false,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);

create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = timezone('utc', now());
  return new;
end;
$$;

drop trigger if exists institutions_set_updated_at on public.institutions;
create trigger institutions_set_updated_at
before update on public.institutions
for each row
execute function public.set_updated_at();

alter table public.institutions enable row level security;

drop policy if exists "Public can read institutions" on public.institutions;
create policy "Public can read institutions"
on public.institutions
for select
to anon, authenticated
using (true);

drop policy if exists "Public can insert institutions" on public.institutions;
create policy "Public can insert institutions"
on public.institutions
for insert
to anon, authenticated
with check (true);

drop policy if exists "Public can update institutions" on public.institutions;
create policy "Public can update institutions"
on public.institutions
for update
to anon, authenticated
using (true)
with check (true);

drop policy if exists "Public can delete institutions" on public.institutions;
create policy "Public can delete institutions"
on public.institutions
for delete
to anon, authenticated
using (true);

insert into storage.buckets (id, name, public)
values ('institution-images', 'institution-images', true)
on conflict (id) do update
set public = excluded.public;

drop policy if exists "Public can view institution images" on storage.objects;
create policy "Public can view institution images"
on storage.objects
for select
to public
using (bucket_id = 'institution-images');

drop policy if exists "Public can upload institution images" on storage.objects;
create policy "Public can upload institution images"
on storage.objects
for insert
to anon, authenticated
with check (bucket_id = 'institution-images');

drop policy if exists "Public can update institution images" on storage.objects;
create policy "Public can update institution images"
on storage.objects
for update
to anon, authenticated
using (bucket_id = 'institution-images')
with check (bucket_id = 'institution-images');

drop policy if exists "Public can delete institution images" on storage.objects;
create policy "Public can delete institution images"
on storage.objects
for delete
to anon, authenticated
using (bucket_id = 'institution-images');
